import type {
  Sushi,
  SushiType,
} from "@/domain/entities/sushi";

const variationNote = "Los ingredientes pueden variar dependiendo del restaurante.";

const typeImages: Record<SushiType, string> = {
  NIGIRI: "/images/types/nigiri.svg",
  MAKI: "/images/types/maki.svg",
  HOSOMAKI: "/images/types/hosomaki.svg",
  FUTOMAKI: "/images/types/futomaki.svg",
  URAMAKI: "/images/types/uramaki.svg",
  TEMAKI: "/images/types/temaki.svg",
  GUNKAN: "/images/types/gunkan.svg",
  SASHIMI: "/images/types/sashimi.svg",
  INARI: "/images/types/inari.svg",
  CHIRASHI: "/images/types/chirashi.svg",
};

type SushiSeedInput = Omit<Sushi, "id" | "imageUrl" | "searchTerms"> & {
  imageUrl?: string | null;
};

function buildSearchTerms(input: SushiSeedInput) {
  return [
    input.name,
    input.japaneseName,
    input.description,
    input.type,
    ...input.ingredients,
    ...input.aliases,
  ]
    .filter(Boolean)
    .join(" ");
}

function createSushi(input: SushiSeedInput): Sushi {
  return {
    ...input,
    id: input.slug,
    imageUrl: input.imageUrl ?? typeImages[input.type],
    searchTerms: buildSearchTerms(input),
  };
}

const sushiSeedInputs: SushiSeedInput[] = [
  {
    name: "Sake Nigiri",
    slug: "sake-nigiri",
    japaneseName: "salmon nigiri",
    description: "Nigiri de salmon fresco sobre arroz avinagrado.",
    type: "NIGIRI",
    ingredients: ["salmon", "arroz de sushi", "wasabi opcional"],
    aliases: ["Salmon Nigiri", "Nigiri de salmon"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Suave y meloso",
    origin: "Tradicion japonesa popular en restaurantes occidentales.",
    popularity: 99,
  },
  {
    name: "Salmon Aburi Nigiri",
    slug: "salmon-aburi-nigiri",
    japaneseName: "aburi sake nigiri",
    description: "Nigiri de salmon ligeramente flameado para un sabor mas untuoso.",
    type: "NIGIRI",
    ingredients: ["salmon ligeramente sellado", "arroz de sushi"],
    aliases: ["Aburi Salmon Nigiri", "Nigiri de salmon flameado"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Tierno y jugoso",
    origin: "Estilo japones adaptado con mucha presencia en cartas modernas.",
    popularity: 88,
  },
  {
    name: "Maguro Nigiri",
    slug: "maguro-nigiri",
    japaneseName: "atun nigiri",
    description: "Nigiri de atun de sabor limpio y textura firme.",
    type: "NIGIRI",
    ingredients: ["atun", "arroz de sushi", "wasabi opcional"],
    aliases: ["Tuna Nigiri", "Nigiri de atun"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Firme y sedosa",
    origin: "Clasico japones muy habitual en menus de sushi.",
    popularity: 93,
  },
  {
    name: "Ebi Nigiri",
    slug: "ebi-nigiri",
    japaneseName: "gamba nigiri",
    description: "Nigiri cubierto con langostino cocido.",
    type: "NIGIRI",
    ingredients: ["langostino cocido", "arroz de sushi"],
    aliases: ["Shrimp Nigiri", "Nigiri de gamba"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "DELICATE",
    texture: "Tierna y ligeramente crujiente",
    origin: "Muy frecuente en combos occidentales por ser una opcion sin crudo.",
    popularity: 90,
  },
  {
    name: "Unagi Nigiri",
    slug: "unagi-nigiri",
    japaneseName: "anguila nigiri",
    description: "Nigiri de anguila glaseada con salsa dulce.",
    type: "NIGIRI",
    ingredients: ["anguila cocinada", "arroz de sushi", "salsa unagi"],
    aliases: ["Eel Nigiri", "Nigiri de anguila"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "BOLD",
    texture: "Melosa y tierna",
    origin: "Muy popular en cartas occidentales por su perfil dulce y ahumado.",
    popularity: 85,
  },
  {
    name: "Hamachi Nigiri",
    slug: "hamachi-nigiri",
    japaneseName: "yellowtail nigiri",
    description: "Nigiri de hamachi con sabor delicado y acabado mantecoso.",
    type: "NIGIRI",
    ingredients: ["hamachi", "arroz de sushi"],
    aliases: ["Yellowtail Nigiri", "Nigiri de hamachi"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "DELICATE",
    texture: "Mantecosa y suave",
    origin: "Pieza habitual en bares de sushi con menu amplio.",
    popularity: 78,
  },
  {
    name: "Tamago Nigiri",
    slug: "tamago-nigiri",
    japaneseName: "tamago nigiri",
    description: "Nigiri coronado con tortilla japonesa ligeramente dulce.",
    type: "NIGIRI",
    ingredients: ["tamago", "arroz de sushi", "nori opcional"],
    aliases: ["Egg Nigiri", "Nigiri de tortilla japonesa"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "DELICATE",
    texture: "Esponjosa y suave",
    origin: "Clasico japones muy comun como opcion sin pescado.",
    popularity: 70,
  },
  {
    name: "Tako Nigiri",
    slug: "tako-nigiri",
    japaneseName: "pulpo nigiri",
    description: "Nigiri de pulpo de textura firme y sabor marino.",
    type: "NIGIRI",
    ingredients: ["pulpo", "arroz de sushi"],
    aliases: ["Octopus Nigiri", "Nigiri de pulpo"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Firme y elastica",
    origin: "Presente en cartas japonesas y menus mixtos occidentales.",
    popularity: 68,
  },
  {
    name: "Ika Nigiri",
    slug: "ika-nigiri",
    japaneseName: "calamar nigiri",
    description: "Nigiri de calamar con sabor limpio y textura suave.",
    type: "NIGIRI",
    ingredients: ["calamar", "arroz de sushi"],
    aliases: ["Squid Nigiri", "Nigiri de calamar"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "DELICATE",
    texture: "Suave y ligeramente firme",
    origin: "Clasico japones conocido en menus especializados.",
    popularity: 66,
  },
  {
    name: "Hotate Nigiri",
    slug: "hotate-nigiri",
    japaneseName: "vieira nigiri",
    description: "Nigiri de vieira con perfil dulce y muy suave.",
    type: "NIGIRI",
    ingredients: ["vieira", "arroz de sushi"],
    aliases: ["Scallop Nigiri", "Nigiri de vieira"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "DELICATE",
    texture: "Sedosa y cremosa",
    origin: "Opcion habitual en restaurantes con carta algo mas premium.",
    popularity: 72,
  },
  {
    name: "Toro Nigiri",
    slug: "toro-nigiri",
    japaneseName: "toro nigiri",
    description: "Nigiri de ventresca de atun, mas grasa y untuosa.",
    type: "NIGIRI",
    ingredients: ["ventresca de atun", "arroz de sushi"],
    aliases: ["Fatty Tuna Nigiri", "Nigiri de toro"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "BOLD",
    texture: "Muy melosa",
    origin: "Pieza muy apreciada en sushi bars y menus especiales.",
    popularity: 76,
  },
  {
    name: "Tekka Maki",
    slug: "tekka-maki",
    japaneseName: "tekka maki",
    description: "Hosomaki de atun, fino y facil de reconocer.",
    type: "HOSOMAKI",
    ingredients: ["atun", "arroz de sushi", "nori"],
    aliases: ["Tuna Maki", "Maki de atun"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Compacta y fresca",
    origin: "Uno de los hosomaki clasicos de la cocina japonesa.",
    popularity: 80,
  },
  {
    name: "Kappa Maki",
    slug: "kappa-maki",
    japaneseName: "kappa maki",
    description: "Hosomaki de pepino, ligero y muy refrescante.",
    type: "HOSOMAKI",
    ingredients: ["pepino", "arroz de sushi", "nori"],
    aliases: ["Cucumber Maki", "Maki de pepino"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "DELICATE",
    texture: "Crujiente y fresca",
    origin: "Clasico vegetal comun en menus y bandejas mixtas.",
    popularity: 67,
  },
  {
    name: "Sake Maki",
    slug: "sake-maki",
    japaneseName: "sake maki",
    description: "Hosomaki de salmon, sencillo y directo.",
    type: "HOSOMAKI",
    ingredients: ["salmon", "arroz de sushi", "nori"],
    aliases: ["Salmon Maki", "Maki de salmon"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Suave y compacta",
    origin: "Uno de los rolls finos mas comunes en menus occidentales.",
    popularity: 79,
  },
  {
    name: "Avocado Maki",
    slug: "avocado-maki",
    japaneseName: "avocado maki",
    description: "Hosomaki de aguacate, simple y cremoso.",
    type: "HOSOMAKI",
    ingredients: ["aguacate", "arroz de sushi", "nori"],
    aliases: ["Maki de aguacate", "Avocado Roll"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "DELICATE",
    texture: "Cremosa",
    origin: "Muy comun en cartas occidentales y opciones vegetarianas.",
    popularity: 73,
  },
  {
    name: "Negitoro Maki",
    slug: "negitoro-maki",
    japaneseName: "negitoro maki",
    description: "Hosomaki relleno de atun graso picado y cebolleta.",
    type: "HOSOMAKI",
    ingredients: ["atun picado", "cebolleta", "arroz de sushi", "nori"],
    aliases: ["Negitoro Roll", "Maki de toro picado"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "BOLD",
    texture: "Untuosa y compacta",
    origin: "Clasico japones presente en menus de nivel medio y alto.",
    popularity: 74,
  },
  {
    name: "Futomaki Clasico",
    slug: "futomaki-clasico",
    japaneseName: "futomaki",
    description: `Roll grueso con varios rellenos vegetales y proteicos. ${variationNote}`,
    type: "FUTOMAKI",
    ingredients: ["arroz de sushi", "nori", "huevo", "pepino", "verduras", "proteina variable"],
    aliases: ["Futomaki", "Roll grueso"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Completa y variada",
    origin: "Formato japones muy extendido con interpretaciones distintas segun el local.",
    popularity: 69,
  },
  {
    name: "California Roll",
    slug: "california-roll",
    japaneseName: null,
    description: "Uramaki con aguacate, pepino y cangrejo o surimi.",
    type: "URAMAKI",
    ingredients: ["surimi o cangrejo", "aguacate", "pepino", "arroz de sushi", "nori", "sesamo"],
    aliases: ["California Maki", "California Uramaki"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Cremosa y fresca",
    origin: "Adaptacion occidental nacida en Estados Unidos.",
    popularity: 100,
  },
  {
    name: "Dragon Roll",
    slug: "dragon-roll",
    japaneseName: null,
    description: `Roll vistoso con cobertura de aguacate y relleno variable, a menudo con anguila o langostino tempura. ${variationNote}`,
    type: "URAMAKI",
    ingredients: ["aguacate", "arroz de sushi", "nori", "relleno variable", "salsa unagi frecuente"],
    aliases: ["Dragon Maki", "Dragon Uramaki"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "BOLD",
    texture: "Cremosa por fuera y jugosa por dentro",
    origin: "Creacion occidental muy comun en delivery y menus fusion.",
    popularity: 95,
  },
  {
    name: "Rainbow Roll",
    slug: "rainbow-roll",
    japaneseName: null,
    description: "Uramaki normalmente cubierto con laminas de varios pescados y aguacate.",
    type: "URAMAKI",
    ingredients: ["arroz de sushi", "nori", "aguacate", "surimi o cangrejo", "varios pescados"],
    aliases: ["Rainbow Maki", "Rainbow Uramaki"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Suave y variada",
    origin: "Roll occidental muy popular en restaurantes de sushi modernos.",
    popularity: 92,
  },
  {
    name: "Philadelphia Roll",
    slug: "philadelphia-roll",
    japaneseName: null,
    description: "Uramaki de salmon y queso crema, muy comun en menus occidentales.",
    type: "URAMAKI",
    ingredients: ["salmon", "queso crema", "pepino o aguacate", "arroz de sushi", "nori"],
    aliases: ["Philly Roll", "Salmon Cream Cheese Roll"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "BOLD",
    texture: "Muy cremosa",
    origin: "Adaptacion occidental muy extendida.",
    popularity: 90,
  },
  {
    name: "Spicy Tuna Roll",
    slug: "spicy-tuna-roll",
    japaneseName: null,
    description: "Uramaki de atun picado con salsa picante.",
    type: "URAMAKI",
    ingredients: ["atun", "mayonesa picante", "arroz de sushi", "nori"],
    aliases: ["Tuna Spicy Roll", "Roll picante de atun"],
    rawFish: true,
    spicyLevel: "MEDIUM",
    flavorIntensity: "BOLD",
    texture: "Cremosa y ligeramente picante",
    origin: "Muy popular en menus de sushi occidental.",
    popularity: 89,
  },
  {
    name: "Spicy Salmon Roll",
    slug: "spicy-salmon-roll",
    japaneseName: null,
    description: "Uramaki de salmon con salsa picante y textura cremosa.",
    type: "URAMAKI",
    ingredients: ["salmon", "mayonesa picante", "arroz de sushi", "nori"],
    aliases: ["Salmon Spicy Roll", "Roll picante de salmon"],
    rawFish: true,
    spicyLevel: "MEDIUM",
    flavorIntensity: "BOLD",
    texture: "Cremosa y jugosa",
    origin: "Version occidental inspirada en los spicy rolls estadounidenses.",
    popularity: 86,
  },
  {
    name: "Alaska Roll",
    slug: "alaska-roll",
    japaneseName: null,
    description: `Uramaki con salmon y aguacate como base habitual. ${variationNote}`,
    type: "URAMAKI",
    ingredients: ["salmon", "aguacate", "pepino opcional", "arroz de sushi", "nori"],
    aliases: ["Alaska Maki", "Alaska Uramaki"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Cremosa y fresca",
    origin: "Roll occidental frecuente en cadenas y restaurantes de delivery.",
    popularity: 82,
  },
  {
    name: "Boston Roll",
    slug: "boston-roll",
    japaneseName: null,
    description: "Uramaki con langostino cocido, aguacate y pepino.",
    type: "URAMAKI",
    ingredients: ["langostino cocido", "aguacate", "pepino", "arroz de sushi", "nori"],
    aliases: ["Boston Maki", "Boston Uramaki"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Fresca y ligera",
    origin: "Adaptacion popular en menus estadounidenses y europeos.",
    popularity: 78,
  },
  {
    name: "Eel Avocado Roll",
    slug: "eel-avocado-roll",
    japaneseName: null,
    description: "Uramaki de anguila cocinada y aguacate.",
    type: "URAMAKI",
    ingredients: ["anguila cocinada", "aguacate", "arroz de sushi", "nori", "salsa unagi"],
    aliases: ["Unagi Avocado Roll", "Roll de anguila y aguacate"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "BOLD",
    texture: "Melosa y cremosa",
    origin: "Muy comun donde triunfan los sabores dulces y ahumados.",
    popularity: 77,
  },
  {
    name: "Salmon Avocado Roll",
    slug: "salmon-avocado-roll",
    japaneseName: null,
    description: "Uramaki de salmon y aguacate, uno de los mas faciles de reconocer.",
    type: "URAMAKI",
    ingredients: ["salmon", "aguacate", "arroz de sushi", "nori"],
    aliases: ["Sake Avocado Roll", "Roll de salmon y aguacate"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Suave y cremosa",
    origin: "Muy habitual en menus occidentales y platos combinados.",
    popularity: 84,
  },
  {
    name: "Tuna Avocado Roll",
    slug: "tuna-avocado-roll",
    japaneseName: null,
    description: "Uramaki de atun y aguacate con perfil suave.",
    type: "URAMAKI",
    ingredients: ["atun", "aguacate", "arroz de sushi", "nori"],
    aliases: ["Maguro Avocado Roll", "Roll de atun y aguacate"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Suave y compacta",
    origin: "Muy conocido en menus de delivery y restaurantes casuales.",
    popularity: 80,
  },
  {
    name: "Shrimp Tempura Roll",
    slug: "shrimp-tempura-roll",
    japaneseName: null,
    description: "Uramaki con langostino en tempura, crujiente por dentro y suave por fuera.",
    type: "URAMAKI",
    ingredients: ["langostino tempura", "aguacate o pepino", "arroz de sushi", "nori"],
    aliases: ["Ebi Tempura Roll", "Tempura Shrimp Roll"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "BOLD",
    texture: "Crujiente y cremosa",
    origin: "Uno de los rolls cocinados mas vendidos en delivery.",
    popularity: 91,
  },
  {
    name: "Crunchy Roll",
    slug: "crunchy-roll",
    japaneseName: null,
    description: `Roll cubierto o relleno con toppings crujientes. ${variationNote}`,
    type: "URAMAKI",
    ingredients: ["arroz de sushi", "nori", "topping crujiente", "relleno variable"],
    aliases: ["Crunch Roll", "Roll crujiente"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "BOLD",
    texture: "Muy crujiente por fuera",
    origin: "Nombre muy comun en cartas de delivery y cocina fusion.",
    popularity: 87,
  },
  {
    name: "Spider Roll",
    slug: "spider-roll",
    japaneseName: null,
    description: "Uramaki con cangrejo de concha blanda frito como relleno principal.",
    type: "URAMAKI",
    ingredients: ["soft shell crab", "lechuga o pepino", "arroz de sushi", "nori"],
    aliases: ["Soft Shell Crab Roll", "Spider Maki"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "BOLD",
    texture: "Crujiente y jugosa",
    origin: "Muy conocido en sushi bars de estilo americano.",
    popularity: 75,
  },
  {
    name: "Volcano Roll",
    slug: "volcano-roll",
    japaneseName: null,
    description: `Roll coronado con mezcla cremosa o gratinada. ${variationNote}`,
    type: "URAMAKI",
    ingredients: ["arroz de sushi", "nori", "relleno variable", "topping cremoso o picante"],
    aliases: ["Volcano Maki", "Volcano Uramaki"],
    rawFish: false,
    spicyLevel: "MEDIUM",
    flavorIntensity: "BOLD",
    texture: "Cremosa y densa",
    origin: "Creacion occidental muy comun en menus de autor y delivery.",
    popularity: 79,
  },
  {
    name: "Dynamite Roll",
    slug: "dynamite-roll",
    japaneseName: null,
    description: `Roll con langostino, mayonesa picante o topping caliente segun el local. ${variationNote}`,
    type: "URAMAKI",
    ingredients: ["langostino", "salsa picante", "arroz de sushi", "nori", "ingredientes variables"],
    aliases: ["Dynamite Maki", "Roll dinamita"],
    rawFish: false,
    spicyLevel: "MEDIUM",
    flavorIntensity: "BOLD",
    texture: "Jugosa y cremosa",
    origin: "Roll occidental muy visto en cartas americanas.",
    popularity: 76,
  },
  {
    name: "Tiger Roll",
    slug: "tiger-roll",
    japaneseName: null,
    description: `Roll con cobertura vistosa y relleno variable, a menudo con langostino y aguacate. ${variationNote}`,
    type: "URAMAKI",
    ingredients: ["langostino frecuente", "aguacate", "arroz de sushi", "nori", "relleno variable"],
    aliases: ["Tiger Maki", "Tiger Uramaki"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Cremosa y compacta",
    origin: "Nombre comercial frecuente en restaurantes de sushi fusion.",
    popularity: 74,
  },
  {
    name: "Soft Shell Crab Roll",
    slug: "soft-shell-crab-roll",
    japaneseName: null,
    description: "Roll de cangrejo de concha blanda frito, muy cercano al Spider Roll.",
    type: "URAMAKI",
    ingredients: ["soft shell crab", "arroz de sushi", "nori", "verduras frescas"],
    aliases: ["Cangrejo de concha blanda roll", "Soft Crab Roll"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "BOLD",
    texture: "Crujiente",
    origin: "Se encuentra sobre todo en cartas amplias de sushi occidental.",
    popularity: 71,
  },
  {
    name: "Vegetable Roll",
    slug: "vegetable-roll",
    japaneseName: null,
    description: `Roll vegetal con combinaciones habituales de pepino, aguacate y zanahoria. ${variationNote}`,
    type: "MAKI",
    ingredients: ["aguacate", "pepino", "zanahoria", "arroz de sushi", "nori"],
    aliases: ["Veggie Roll", "Maki vegetal"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "DELICATE",
    texture: "Fresca y crujiente",
    origin: "Muy comun en menus vegetarianos y combinados.",
    popularity: 72,
  },
  {
    name: "Salmon Skin Roll",
    slug: "salmon-skin-roll",
    japaneseName: null,
    description: "Roll de piel de salmon cocinada, con sabor intenso y toque crujiente.",
    type: "MAKI",
    ingredients: ["piel de salmon cocinada", "pepino", "arroz de sushi", "nori"],
    aliases: ["Skin Roll", "Roll de piel de salmon"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "BOLD",
    texture: "Crujiente y jugosa",
    origin: "Popular en cartas occidentales con rolls cocinados.",
    popularity: 70,
  },
  {
    name: "Tempura Roll",
    slug: "tempura-roll",
    japaneseName: null,
    description: `Roll elaborado con algun relleno en tempura o incluso rebozado por fuera. ${variationNote}`,
    type: "MAKI",
    ingredients: ["arroz de sushi", "nori", "relleno tempura", "ingredientes variables"],
    aliases: ["Tempura Maki", "Roll tempura"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "BOLD",
    texture: "Crujiente",
    origin: "Etiqueta muy comun en menus de delivery.",
    popularity: 73,
  },
  {
    name: "Salmon Temaki",
    slug: "salmon-temaki",
    japaneseName: "sake temaki",
    description: "Cono de nori relleno de arroz y salmon.",
    type: "TEMAKI",
    ingredients: ["salmon", "arroz de sushi", "nori", "verduras opcionales"],
    aliases: ["Sake Temaki", "Temaki de salmon"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Crujiente por fuera y suave por dentro",
    origin: "Temaki muy frecuente en restaurantes occidentales.",
    popularity: 81,
  },
  {
    name: "Spicy Tuna Temaki",
    slug: "spicy-tuna-temaki",
    japaneseName: null,
    description: "Temaki de atun con salsa picante.",
    type: "TEMAKI",
    ingredients: ["atun", "mayonesa picante", "arroz de sushi", "nori"],
    aliases: ["Temaki picante de atun", "Tuna Spicy Temaki"],
    rawFish: true,
    spicyLevel: "MEDIUM",
    flavorIntensity: "BOLD",
    texture: "Crujiente y cremosa",
    origin: "Muy presente en menus de sushi casual.",
    popularity: 79,
  },
  {
    name: "California Temaki",
    slug: "california-temaki",
    japaneseName: null,
    description: "Version en cono del relleno tipo California.",
    type: "TEMAKI",
    ingredients: ["surimi o cangrejo", "aguacate", "pepino", "arroz de sushi", "nori"],
    aliases: ["Temaki California", "California Hand Roll"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Fresca y cremosa",
    origin: "Adaptacion occidental habitual en delivery.",
    popularity: 76,
  },
  {
    name: "Tempura Prawn Temaki",
    slug: "tempura-prawn-temaki",
    japaneseName: null,
    description: "Temaki con langostino tempura y textura crujiente.",
    type: "TEMAKI",
    ingredients: ["langostino tempura", "arroz de sushi", "nori", "salsa frecuente"],
    aliases: ["Ebi Tempura Temaki", "Temaki de gamba tempura"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "BOLD",
    texture: "Crujiente y jugosa",
    origin: "Muy comun en menus con opciones cocinadas.",
    popularity: 75,
  },
  {
    name: "Ikura Gunkan",
    slug: "ikura-gunkan",
    japaneseName: "ikura gunkan",
    description: "Gunkan rematado con huevas de salmon.",
    type: "GUNKAN",
    ingredients: ["ikura", "arroz de sushi", "nori"],
    aliases: ["Salmon Roe Gunkan", "Gunkan de ikura"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "BOLD",
    texture: "Brillante y jugosa",
    origin: "Clasico japones muy reconocible visualmente.",
    popularity: 77,
  },
  {
    name: "Tobiko Gunkan",
    slug: "tobiko-gunkan",
    japaneseName: "tobiko gunkan",
    description: "Gunkan con huevas de pez volador, pequenas y crujientes.",
    type: "GUNKAN",
    ingredients: ["tobiko", "arroz de sushi", "nori"],
    aliases: ["Flying Fish Roe Gunkan", "Gunkan de tobiko"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Pequena y crujiente",
    origin: "Comun en menus de sushi con piezas especiales.",
    popularity: 74,
  },
  {
    name: "Spicy Tuna Gunkan",
    slug: "spicy-tuna-gunkan",
    japaneseName: null,
    description: "Gunkan con atun picado y aderezo picante.",
    type: "GUNKAN",
    ingredients: ["atun picado", "mayonesa picante", "arroz de sushi", "nori"],
    aliases: ["Gunkan picante de atun", "Tuna Gunkan"],
    rawFish: true,
    spicyLevel: "MEDIUM",
    flavorIntensity: "BOLD",
    texture: "Cremosa",
    origin: "Version moderna muy comun en restaurantes occidentales.",
    popularity: 73,
  },
  {
    name: "Wakame Gunkan",
    slug: "wakame-gunkan",
    japaneseName: null,
    description: "Gunkan coronado con ensalada de algas wakame.",
    type: "GUNKAN",
    ingredients: ["wakame", "arroz de sushi", "nori", "sesamo frecuente"],
    aliases: ["Seaweed Gunkan", "Gunkan de wakame"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Jugosa y ligeramente crujiente",
    origin: "Muy visto como opcion sin pescado.",
    popularity: 68,
  },
  {
    name: "Salmon Sashimi",
    slug: "salmon-sashimi",
    japaneseName: "sake sashimi",
    description: "Laminas de salmon sin arroz.",
    type: "SASHIMI",
    ingredients: ["salmon"],
    aliases: ["Sake Sashimi", "Sashimi de salmon"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Suave y limpia",
    origin: "Uno de los sashimi mas pedidos en cartas occidentales.",
    popularity: 94,
  },
  {
    name: "Tuna Sashimi",
    slug: "tuna-sashimi",
    japaneseName: "maguro sashimi",
    description: "Laminas de atun servidas sin arroz.",
    type: "SASHIMI",
    ingredients: ["atun"],
    aliases: ["Maguro Sashimi", "Sashimi de atun"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Firme y sedosa",
    origin: "Clasico japones muy habitual.",
    popularity: 92,
  },
  {
    name: "Mixed Sashimi",
    slug: "mixed-sashimi",
    japaneseName: "moriawase sashimi",
    description: `Surtido de diferentes cortes de pescado y marisco. ${variationNote}`,
    type: "SASHIMI",
    ingredients: ["pescados variados", "mariscos variados"],
    aliases: ["Sashimi Mix", "Surtido de sashimi"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Variada segun las piezas",
    origin: "Muy popular para compartir o probar varios pescados.",
    popularity: 90,
  },
  {
    name: "Hamachi Sashimi",
    slug: "hamachi-sashimi",
    japaneseName: "hamachi sashimi",
    description: "Cortes de hamachi con perfil mantecoso.",
    type: "SASHIMI",
    ingredients: ["hamachi"],
    aliases: ["Yellowtail Sashimi", "Sashimi de hamachi"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "DELICATE",
    texture: "Muy suave",
    origin: "Comun en sushi bars con carta amplia.",
    popularity: 76,
  },
  {
    name: "Inari Sushi",
    slug: "inari-sushi",
    japaneseName: "inarizushi",
    description: "Bolsa de tofu frito dulce rellena de arroz.",
    type: "INARI",
    ingredients: ["tofu frito sazonado", "arroz de sushi"],
    aliases: ["Inari", "Tofu Pouch Sushi"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Suave y jugosa",
    origin: "Clasico japones tambien frecuente en opciones vegetarianas.",
    popularity: 72,
  },
  {
    name: "Chirashi Bowl",
    slug: "chirashi-bowl",
    japaneseName: "chirashizushi",
    description: `Bol de arroz de sushi con varias coberturas de pescado y verduras. ${variationNote}`,
    type: "CHIRASHI",
    ingredients: ["arroz de sushi", "pescados variados", "verduras", "toppings variables"],
    aliases: ["Chirashi", "Sushi Bowl"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Variada y abundante",
    origin: "Plato japones completo muy adaptado al formato bowl.",
    popularity: 83,
  },
  {
    name: "Salmon Chirashi",
    slug: "salmon-chirashi",
    japaneseName: null,
    description: "Chirashi centrado en salmon sobre arroz de sushi.",
    type: "CHIRASHI",
    ingredients: ["salmon", "arroz de sushi", "verduras o toppings opcionales"],
    aliases: ["Sake Chirashi", "Chirashi de salmon"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Suave y abundante",
    origin: "Opcion muy comun cuando el local ofrece sushi bowls.",
    popularity: 80,
  },
  {
    name: "Tuna Chirashi",
    slug: "tuna-chirashi",
    japaneseName: null,
    description: "Chirashi de atun servido sobre arroz de sushi.",
    type: "CHIRASHI",
    ingredients: ["atun", "arroz de sushi", "verduras o toppings opcionales"],
    aliases: ["Maguro Chirashi", "Chirashi de atun"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Firme y abundante",
    origin: "Bowl frecuente en cartas de sushi mas amplias.",
    popularity: 78,
  },
];

export const sushiSeedCatalog = sushiSeedInputs.map(createSushi);

export const sushiSeedStats = {
  total: sushiSeedCatalog.length,
  rawFishCount: sushiSeedCatalog.filter((sushi) => sushi.rawFish).length,
};

export type SushiSeedRecord = (typeof sushiSeedCatalog)[number];
