import type {
  FlavorIntensity,
  SpicyLevel,
  Sushi,
  SushiType,
} from "@/domain/entities/sushi";

const variationNote = "Puede variar dependiendo del restaurante.";

type CatalogInput = {
  name: string;
  japaneseName: string | null;
  aliases: string[];
  type: SushiType;
  shortDescription: string;
  ingredients: string[];
  rawFish: boolean;
  spicyLevel: SpicyLevel;
  flavorIntensity: FlavorIntensity;
  texture: string;
  origin: string;
  popularity?: number;
  imageUrl?: string | null;
};

function slugify(value: string) {
  return value
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/&/g, " and ")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function buildSearchTerms(input: CatalogInput) {
  return [
    input.name,
    input.japaneseName,
    input.shortDescription,
    input.type,
    ...input.ingredients,
    ...input.aliases,
  ]
    .filter(Boolean)
    .join(" ");
}

function entry(input: CatalogInput): Sushi {
  const slug = slugify(input.name);

  return {
    id: slug,
    slug,
    name: input.name,
    japaneseName: input.japaneseName,
    aliases: input.aliases,
    type: input.type,
    shortDescription: input.shortDescription,
    ingredients: input.ingredients,
    rawFish: input.rawFish,
    spicyLevel: input.spicyLevel,
    flavorIntensity: input.flavorIntensity,
    texture: input.texture,
    origin: input.origin,
    popularity: input.popularity ?? 55,
    imageUrl: input.imageUrl ?? `/images/sushi/${slug}.png`,
    searchTerms: buildSearchTerms(input),
  };
}

const rawCatalog: CatalogInput[] = [
  {
    name: "Sake Nigiri",
    japaneseName: "sake nigiri",
    aliases: ["Salmon Nigiri", "Nigiri de salmon"],
    type: "NIGIRI",
    shortDescription: "Nigiri de salmon sobre arroz avinagrado.",
    ingredients: ["salmon", "arroz de sushi", "wasabi opcional"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Suave y melosa",
    origin: "Clasico japones muy habitual en cartas europeas.",
    popularity: 99,
  },
  {
    name: "Aburi Sake Nigiri",
    japaneseName: "aburi sake nigiri",
    aliases: ["Salmon Aburi Nigiri", "Nigiri de salmon flameado"],
    type: "NIGIRI",
    shortDescription: "Nigiri de salmon ligeramente flameado.",
    ingredients: ["salmon flameado", "arroz de sushi", "salsa opcional"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Tierno y untuoso",
    origin: "Estilo japones moderno muy comun en restaurantes de sushi.",
    popularity: 90,
  },
  {
    name: "Maguro Nigiri",
    japaneseName: "maguro nigiri",
    aliases: ["Tuna Nigiri", "Nigiri de atun"],
    type: "NIGIRI",
    shortDescription: "Nigiri de atun de sabor limpio.",
    ingredients: ["atun", "arroz de sushi", "wasabi opcional"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Firme y sedosa",
    origin: "Clasico japones presente en casi todos los menus.",
    popularity: 94,
  },
  {
    name: "Toro Nigiri",
    japaneseName: "toro nigiri",
    aliases: ["Fatty Tuna Nigiri", "Nigiri de ventresca de atun"],
    type: "NIGIRI",
    shortDescription: "Nigiri de ventresca de atun, mas graso y meloso.",
    ingredients: ["ventresca de atun", "arroz de sushi"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "BOLD",
    texture: "Muy melosa",
    origin: "Pieza apreciada en sushi bars y cartas premium.",
    popularity: 78,
  },
  {
    name: "Ebi Nigiri",
    japaneseName: "ebi nigiri",
    aliases: ["Shrimp Nigiri", "Nigiri de gamba", "Nigiri de langostino"],
    type: "NIGIRI",
    shortDescription: "Nigiri con langostino cocido.",
    ingredients: ["langostino cocido", "arroz de sushi"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "DELICATE",
    texture: "Tierna y firme",
    origin: "Opcion sin crudo muy comun en menus europeos.",
    popularity: 91,
  },
  {
    name: "Amaebi Nigiri",
    japaneseName: "amaebi nigiri",
    aliases: ["Sweet Shrimp Nigiri", "Nigiri de gamba dulce"],
    type: "NIGIRI",
    shortDescription: "Nigiri de gamba dulce servida cruda o muy poco tratada.",
    ingredients: ["gamba dulce", "arroz de sushi"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "DELICATE",
    texture: "Suave y delicada",
    origin: "Pieza japonesa que aparece en cartas amplias.",
    popularity: 63,
  },
  {
    name: "Unagi Nigiri",
    japaneseName: "unagi nigiri",
    aliases: ["Eel Nigiri", "Nigiri de anguila"],
    type: "NIGIRI",
    shortDescription: "Nigiri de anguila cocinada con salsa dulce.",
    ingredients: ["anguila cocinada", "arroz de sushi", "salsa unagi"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "BOLD",
    texture: "Melosa y tierna",
    origin: "Clasico japones muy popular por su perfil dulce y ahumado.",
    popularity: 85,
  },
  {
    name: "Anago Nigiri",
    japaneseName: "anago nigiri",
    aliases: ["Sea Eel Nigiri", "Nigiri de anguila de mar"],
    type: "NIGIRI",
    shortDescription: "Nigiri de anguila de mar cocinada, mas suave que unagi.",
    ingredients: ["anago cocinado", "arroz de sushi", "salsa dulce opcional"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Tierna",
    origin: "Tradicional japones, menos frecuente que unagi en Europa.",
    popularity: 58,
  },
  {
    name: "Hamachi Nigiri",
    japaneseName: "hamachi nigiri",
    aliases: ["Yellowtail Nigiri", "Nigiri de hamachi"],
    type: "NIGIRI",
    shortDescription: "Nigiri de hamachi con sabor delicado.",
    ingredients: ["hamachi", "arroz de sushi"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "DELICATE",
    texture: "Mantecosa y suave",
    origin: "Pieza habitual en restaurantes con carta amplia.",
    popularity: 77,
  },
  {
    name: "Tai Nigiri",
    japaneseName: "tai nigiri",
    aliases: ["Sea Bream Nigiri", "Nigiri de dorada"],
    type: "NIGIRI",
    shortDescription: "Nigiri de dorada o pescado blanco similar.",
    ingredients: ["dorada", "arroz de sushi"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "DELICATE",
    texture: "Firme y limpia",
    origin: "Clasico japones de pescado blanco.",
    popularity: 61,
  },
  {
    name: "Suzuki Nigiri",
    japaneseName: "suzuki nigiri",
    aliases: ["Sea Bass Nigiri", "Nigiri de lubina"],
    type: "NIGIRI",
    shortDescription: "Nigiri de lubina de sabor suave.",
    ingredients: ["lubina", "arroz de sushi"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "DELICATE",
    texture: "Firme y ligera",
    origin: "Pescado blanco comun en cartas europeas.",
    popularity: 62,
  },
  {
    name: "Saba Nigiri",
    japaneseName: "saba nigiri",
    aliases: ["Mackerel Nigiri", "Nigiri de caballa"],
    type: "NIGIRI",
    shortDescription: "Nigiri de caballa, a menudo marinada o curada.",
    ingredients: ["caballa", "arroz de sushi", "vinagre opcional"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "BOLD",
    texture: "Firme y grasa",
    origin: "Pieza japonesa clasica, menos popular para principiantes.",
    popularity: 55,
  },
  {
    name: "Ika Nigiri",
    japaneseName: "ika nigiri",
    aliases: ["Squid Nigiri", "Nigiri de calamar"],
    type: "NIGIRI",
    shortDescription: "Nigiri de calamar de sabor limpio.",
    ingredients: ["calamar", "arroz de sushi"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "DELICATE",
    texture: "Suave y elastica",
    origin: "Clasico japones presente en cartas especializadas.",
    popularity: 60,
  },
  {
    name: "Tako Nigiri",
    japaneseName: "tako nigiri",
    aliases: ["Octopus Nigiri", "Nigiri de pulpo"],
    type: "NIGIRI",
    shortDescription: "Nigiri de pulpo cocido.",
    ingredients: ["pulpo cocido", "arroz de sushi"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Firme y elastica",
    origin: "Pieza clasica que aparece en menus mixtos.",
    popularity: 67,
  },
  {
    name: "Hotate Nigiri",
    japaneseName: "hotate nigiri",
    aliases: ["Scallop Nigiri", "Nigiri de vieira"],
    type: "NIGIRI",
    shortDescription: "Nigiri de vieira de sabor dulce.",
    ingredients: ["vieira", "arroz de sushi"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "DELICATE",
    texture: "Sedosa y cremosa",
    origin: "Pieza habitual en cartas premium.",
    popularity: 72,
  },
  {
    name: "Hokkigai Nigiri",
    japaneseName: "hokkigai nigiri",
    aliases: ["Surf Clam Nigiri", "Nigiri de almeja"],
    type: "NIGIRI",
    shortDescription: "Nigiri de almeja o surf clam.",
    ingredients: ["almeja hokkigai", "arroz de sushi"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Firme y carnosa",
    origin: "Pieza japonesa presente en cartas amplias.",
    popularity: 48,
  },
  {
    name: "Kani Nigiri",
    japaneseName: "kani nigiri",
    aliases: ["Crab Nigiri", "Nigiri de cangrejo", "Nigiri de surimi"],
    type: "NIGIRI",
    shortDescription: "Nigiri de cangrejo o surimi, segun el restaurante.",
    ingredients: ["cangrejo o surimi", "arroz de sushi"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "DELICATE",
    texture: "Suave y fibrosa",
    origin: `Comun en cartas occidentales. ${variationNote}`,
    popularity: 70,
  },
  {
    name: "Ikura Nigiri",
    japaneseName: "ikura nigiri",
    aliases: ["Salmon Roe Nigiri", "Nigiri de huevas de salmon"],
    type: "NIGIRI",
    shortDescription: "Nigiri con huevas de salmon.",
    ingredients: ["ikura", "arroz de sushi", "nori opcional"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "BOLD",
    texture: "Jugosa y perlada",
    origin: "Mas frecuente en formato gunkan, pero aparece en cartas variadas.",
    popularity: 58,
  },
  {
    name: "Tobiko Nigiri",
    japaneseName: "tobiko nigiri",
    aliases: ["Flying Fish Roe Nigiri", "Nigiri de tobiko"],
    type: "NIGIRI",
    shortDescription: "Nigiri con huevas de pez volador.",
    ingredients: ["tobiko", "arroz de sushi", "nori opcional"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Crujiente y pequena",
    origin: "Mas habitual como topping o gunkan.",
    popularity: 55,
  },
  {
    name: "Tamago Nigiri",
    japaneseName: "tamago nigiri",
    aliases: ["Egg Nigiri", "Nigiri de tortilla japonesa"],
    type: "NIGIRI",
    shortDescription: "Nigiri de tortilla japonesa ligeramente dulce.",
    ingredients: ["tamago", "arroz de sushi", "nori opcional"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "DELICATE",
    texture: "Esponjosa y suave",
    origin: "Clasico japones y opcion sin pescado.",
    popularity: 73,
  },
  {
    name: "Avocado Nigiri",
    japaneseName: null,
    aliases: ["Avocado Sushi", "Nigiri de aguacate"],
    type: "NIGIRI",
    shortDescription: "Nigiri vegetal con lamina de aguacate.",
    ingredients: ["aguacate", "arroz de sushi", "nori opcional"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "DELICATE",
    texture: "Cremosa",
    origin: "Adaptacion vegetal frecuente en Europa.",
    popularity: 69,
  },
  {
    name: "Shiitake Nigiri",
    japaneseName: "shiitake nigiri",
    aliases: ["Mushroom Nigiri", "Nigiri de shiitake"],
    type: "NIGIRI",
    shortDescription: "Nigiri de seta shiitake cocinada o marinada.",
    ingredients: ["shiitake", "arroz de sushi", "salsa opcional"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Tierna y carnosa",
    origin: "Opcion vegetal presente en algunos menus.",
    popularity: 47,
  },
  {
    name: "Pez Mantequilla Nigiri",
    japaneseName: null,
    aliases: ["Butterfish Nigiri", "Escolar Nigiri", "Nigiri de pez mantequilla"],
    type: "NIGIRI",
    shortDescription: "Nigiri de pescado blanco graso conocido como pez mantequilla.",
    ingredients: ["pez mantequilla", "arroz de sushi"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Mantecosa",
    origin: "Muy comun en cartas espanolas de sushi.",
    popularity: 76,
  },
  {
    name: "Foie Nigiri",
    japaneseName: null,
    aliases: ["Foie Gras Nigiri", "Nigiri de foie"],
    type: "NIGIRI",
    shortDescription: "Nigiri fusion con foie, normalmente marcado o flameado.",
    ingredients: ["foie", "arroz de sushi", "salsa dulce opcional"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "BOLD",
    texture: "Muy untuosa",
    origin: `Fusion habitual en restaurantes japoneses de Espana. ${variationNote}`,
    popularity: 64,
  },
  {
    name: "Wagyu Nigiri",
    japaneseName: null,
    aliases: ["Beef Nigiri", "Nigiri de wagyu", "Nigiri de ternera"],
    type: "NIGIRI",
    shortDescription: "Nigiri fusion con carne marcada o flameada.",
    ingredients: ["wagyu o ternera", "arroz de sushi", "salsa opcional"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "BOLD",
    texture: "Tierna y grasa",
    origin: `Fusion moderna en cartas premium. ${variationNote}`,
    popularity: 62,
  },

  {
    name: "Maki Mixto",
    japaneseName: null,
    aliases: ["Mixed Maki", "Surtido de maki"],
    type: "MAKI",
    shortDescription: "Surtido de piezas maki con varios rellenos.",
    ingredients: ["arroz de sushi", "nori", "rellenos variados"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Compacta y variada",
    origin: `Formato de menu habitual en delivery. ${variationNote}`,
    popularity: 80,
  },
  {
    name: "Maki Salmon Queso",
    japaneseName: null,
    aliases: ["Salmon Cheese Maki", "Maki de salmon y queso"],
    type: "MAKI",
    shortDescription: "Maki con salmon y queso crema.",
    ingredients: ["salmon", "queso crema", "arroz de sushi", "nori"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Cremosa y compacta",
    origin: "Adaptacion occidental muy comun en Europa.",
    popularity: 78,
  },
  {
    name: "Maki Atun Aguacate",
    japaneseName: null,
    aliases: ["Tuna Avocado Maki", "Maki de atun y aguacate"],
    type: "MAKI",
    shortDescription: "Maki con atun y aguacate.",
    ingredients: ["atun", "aguacate", "arroz de sushi", "nori"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Suave y compacta",
    origin: "Combinacion habitual en cartas occidentales.",
    popularity: 72,
  },
  {
    name: "Maki Salmon Aguacate",
    japaneseName: null,
    aliases: ["Salmon Avocado Maki", "Maki de salmon y aguacate"],
    type: "MAKI",
    shortDescription: "Maki con salmon y aguacate.",
    ingredients: ["salmon", "aguacate", "arroz de sushi", "nori"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Suave y cremosa",
    origin: "Muy comun en menus europeos.",
    popularity: 82,
  },
  {
    name: "Maki Vegetal",
    japaneseName: null,
    aliases: ["Vegetable Maki", "Veggie Maki"],
    type: "MAKI",
    shortDescription: "Maki vegetal con rellenos frescos.",
    ingredients: ["aguacate", "pepino", "zanahoria", "arroz de sushi", "nori"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "DELICATE",
    texture: "Fresca y crujiente",
    origin: `Opcion vegetariana comun. ${variationNote}`,
    popularity: 70,
  },
  {
    name: "Maki Tempura",
    japaneseName: null,
    aliases: ["Tempura Maki", "Maki rebozado"],
    type: "MAKI",
    shortDescription: "Maki con relleno en tempura o acabado crujiente.",
    ingredients: ["arroz de sushi", "nori", "relleno en tempura"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "BOLD",
    texture: "Crujiente y compacta",
    origin: `Comun en cartas de delivery. ${variationNote}`,
    popularity: 69,
  },

  {
    name: "Tekka Maki",
    japaneseName: "tekka maki",
    aliases: ["Tuna Maki", "Maki de atun"],
    type: "HOSOMAKI",
    shortDescription: "Hosomaki fino de atun.",
    ingredients: ["atun", "arroz de sushi", "nori"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Firme y compacta",
    origin: "Hosomaki clasico japones.",
    popularity: 82,
  },
  {
    name: "Sake Maki",
    japaneseName: "sake maki",
    aliases: ["Salmon Maki", "Maki de salmon"],
    type: "HOSOMAKI",
    shortDescription: "Hosomaki fino de salmon.",
    ingredients: ["salmon", "arroz de sushi", "nori"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Suave y compacta",
    origin: "Muy comun en menus europeos.",
    popularity: 86,
  },
  {
    name: "Kappa Maki",
    japaneseName: "kappa maki",
    aliases: ["Cucumber Maki", "Maki de pepino"],
    type: "HOSOMAKI",
    shortDescription: "Hosomaki de pepino.",
    ingredients: ["pepino", "arroz de sushi", "nori"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "DELICATE",
    texture: "Crujiente y fresca",
    origin: "Hosomaki vegetal clasico.",
    popularity: 68,
  },
  {
    name: "Avocado Maki",
    japaneseName: null,
    aliases: ["Maki de aguacate", "Avocado Hosomaki"],
    type: "HOSOMAKI",
    shortDescription: "Hosomaki de aguacate.",
    ingredients: ["aguacate", "arroz de sushi", "nori"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "DELICATE",
    texture: "Cremosa",
    origin: "Adaptacion vegetal muy popular.",
    popularity: 74,
  },
  {
    name: "Oshinko Maki",
    japaneseName: "oshinko maki",
    aliases: ["Pickled Radish Maki", "Maki de daikon encurtido"],
    type: "HOSOMAKI",
    shortDescription: "Hosomaki con rabanito japones encurtido.",
    ingredients: ["daikon encurtido", "arroz de sushi", "nori"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Crujiente",
    origin: "Hosomaki vegetal japones.",
    popularity: 45,
  },
  {
    name: "Kanpyo Maki",
    japaneseName: "kanpyo maki",
    aliases: ["Gourd Maki", "Maki de calabaza seca"],
    type: "HOSOMAKI",
    shortDescription: "Hosomaki con tiras de calabaza seca cocida.",
    ingredients: ["kanpyo", "arroz de sushi", "nori"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Tierna y fibrosa",
    origin: "Relleno tradicional japones.",
    popularity: 42,
  },
  {
    name: "Negitoro Maki",
    japaneseName: "negitoro maki",
    aliases: ["Chopped Fatty Tuna Maki", "Maki de toro picado"],
    type: "HOSOMAKI",
    shortDescription: "Hosomaki de atun graso picado con cebolleta.",
    ingredients: ["atun graso picado", "cebolleta", "arroz de sushi", "nori"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "BOLD",
    texture: "Untuosa y compacta",
    origin: "Clasico japones en cartas especializadas.",
    popularity: 75,
  },
  {
    name: "Tamago Maki",
    japaneseName: "tamago maki",
    aliases: ["Egg Maki", "Maki de tortilla japonesa"],
    type: "HOSOMAKI",
    shortDescription: "Hosomaki de tortilla japonesa.",
    ingredients: ["tamago", "arroz de sushi", "nori"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "DELICATE",
    texture: "Suave y esponjosa",
    origin: "Opcion sin pescado comun.",
    popularity: 58,
  },
  {
    name: "Ebi Maki",
    japaneseName: "ebi maki",
    aliases: ["Shrimp Maki", "Maki de gamba"],
    type: "HOSOMAKI",
    shortDescription: "Hosomaki de langostino cocido.",
    ingredients: ["langostino cocido", "arroz de sushi", "nori"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "DELICATE",
    texture: "Tierna y compacta",
    origin: "Comun en menus para usuarios que evitan pescado crudo.",
    popularity: 66,
  },
  {
    name: "Unakyu Maki",
    japaneseName: "unakyu maki",
    aliases: ["Unagi Cucumber Maki", "Maki de anguila y pepino"],
    type: "HOSOMAKI",
    shortDescription: "Hosomaki de anguila cocinada y pepino.",
    ingredients: ["anguila cocinada", "pepino", "arroz de sushi", "nori"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "BOLD",
    texture: "Melosa y crujiente",
    origin: "Combinacion japonesa conocida.",
    popularity: 60,
  },
  {
    name: "Spicy Tuna Hosomaki",
    japaneseName: null,
    aliases: ["Spicy Tuna Maki", "Maki picante de atun"],
    type: "HOSOMAKI",
    shortDescription: "Hosomaki de atun con salsa picante.",
    ingredients: ["atun", "salsa picante", "arroz de sushi", "nori"],
    rawFish: true,
    spicyLevel: "MEDIUM",
    flavorIntensity: "BOLD",
    texture: "Compacta y cremosa",
    origin: "Adaptacion occidental frecuente.",
    popularity: 70,
  },
  {
    name: "Spicy Salmon Hosomaki",
    japaneseName: null,
    aliases: ["Spicy Salmon Maki", "Maki picante de salmon"],
    type: "HOSOMAKI",
    shortDescription: "Hosomaki de salmon con salsa picante.",
    ingredients: ["salmon", "salsa picante", "arroz de sushi", "nori"],
    rawFish: true,
    spicyLevel: "MEDIUM",
    flavorIntensity: "BOLD",
    texture: "Compacta y jugosa",
    origin: "Adaptacion occidental frecuente.",
    popularity: 68,
  },
  {
    name: "Wakame Maki",
    japaneseName: null,
    aliases: ["Seaweed Maki", "Maki de wakame"],
    type: "HOSOMAKI",
    shortDescription: "Hosomaki vegetal con ensalada de algas.",
    ingredients: ["wakame", "arroz de sushi", "nori", "sesamo opcional"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Jugosa y ligeramente crujiente",
    origin: "Opcion vegetal frecuente en Europa.",
    popularity: 53,
  },
  {
    name: "Shiitake Maki",
    japaneseName: null,
    aliases: ["Mushroom Maki", "Maki de shiitake"],
    type: "HOSOMAKI",
    shortDescription: "Hosomaki de seta shiitake.",
    ingredients: ["shiitake", "arroz de sushi", "nori"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Tierna",
    origin: "Relleno vegetal presente en algunos restaurantes.",
    popularity: 44,
  },

  {
    name: "Futomaki Clasico",
    japaneseName: "futomaki",
    aliases: ["Futomaki", "Roll grueso"],
    type: "FUTOMAKI",
    shortDescription: `Roll grueso con varios rellenos vegetales y proteicos. ${variationNote}`,
    ingredients: ["arroz de sushi", "nori", "tamago", "pepino", "rellenos variados"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Completa y variada",
    origin: "Formato tradicional japones con muchas versiones.",
    popularity: 70,
  },
  {
    name: "Ebi Futomaki",
    japaneseName: null,
    aliases: ["Shrimp Futomaki", "Futomaki de gamba"],
    type: "FUTOMAKI",
    shortDescription: `Futomaki con langostino y verduras. ${variationNote}`,
    ingredients: ["langostino", "pepino", "aguacate", "arroz de sushi", "nori"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Jugosa y variada",
    origin: "Adaptacion comun en cartas europeas.",
    popularity: 62,
  },
  {
    name: "Salmon Futomaki",
    japaneseName: null,
    aliases: ["Futomaki de salmon"],
    type: "FUTOMAKI",
    shortDescription: `Futomaki con salmon y rellenos frescos. ${variationNote}`,
    ingredients: ["salmon", "aguacate", "pepino", "arroz de sushi", "nori"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Suave y completa",
    origin: "Version occidental frecuente.",
    popularity: 67,
  },
  {
    name: "Vegetable Futomaki",
    japaneseName: null,
    aliases: ["Futomaki vegetal", "Veggie Futomaki"],
    type: "FUTOMAKI",
    shortDescription: `Futomaki con rellenos vegetales variados. ${variationNote}`,
    ingredients: ["aguacate", "pepino", "zanahoria", "tamago opcional", "arroz de sushi", "nori"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "DELICATE",
    texture: "Crujiente y fresca",
    origin: "Opcion vegetariana comun.",
    popularity: 60,
  },
  {
    name: "California Futomaki",
    japaneseName: null,
    aliases: ["Futomaki California"],
    type: "FUTOMAKI",
    shortDescription: `Futomaki inspirado en California Roll. ${variationNote}`,
    ingredients: ["surimi o cangrejo", "aguacate", "pepino", "arroz de sushi", "nori"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Cremosa y fresca",
    origin: "Fusion occidental basada en un roll muy popular.",
    popularity: 64,
  },
  {
    name: "Tempura Futomaki",
    japaneseName: null,
    aliases: ["Futomaki tempura", "Fried Futomaki"],
    type: "FUTOMAKI",
    shortDescription: `Futomaki con relleno o exterior en tempura. ${variationNote}`,
    ingredients: ["arroz de sushi", "nori", "relleno tempura", "salsa opcional"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "BOLD",
    texture: "Crujiente y densa",
    origin: "Muy comun en cartas de delivery.",
    popularity: 66,
  },
  {
    name: "Spicy Tuna Futomaki",
    japaneseName: null,
    aliases: ["Futomaki picante de atun"],
    type: "FUTOMAKI",
    shortDescription: `Futomaki con atun y salsa picante. ${variationNote}`,
    ingredients: ["atun", "salsa picante", "pepino", "arroz de sushi", "nori"],
    rawFish: true,
    spicyLevel: "MEDIUM",
    flavorIntensity: "BOLD",
    texture: "Cremosa y compacta",
    origin: "Fusion occidental frecuente.",
    popularity: 61,
  },
  {
    name: "Soft Shell Crab Futomaki",
    japaneseName: null,
    aliases: ["Futomaki de cangrejo crujiente"],
    type: "FUTOMAKI",
    shortDescription: `Futomaki con cangrejo de concha blanda frito. ${variationNote}`,
    ingredients: ["soft shell crab", "lechuga o pepino", "arroz de sushi", "nori"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "BOLD",
    texture: "Crujiente y jugosa",
    origin: "Fusion japonesa-americana presente en cartas amplias.",
    popularity: 54,
  },

  {
    name: "California Uramaki",
    japaneseName: null,
    aliases: ["California Roll", "California Maki"],
    type: "URAMAKI",
    shortDescription: `Uramaki con surimi o cangrejo, aguacate y pepino. ${variationNote}`,
    ingredients: ["surimi o cangrejo", "aguacate", "pepino", "arroz de sushi", "nori", "sesamo"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Cremosa y fresca",
    origin: "Roll occidental ampliamente integrado en menus europeos.",
    popularity: 100,
  },
  {
    name: "Salmon Avocado Uramaki",
    japaneseName: null,
    aliases: ["Salmon Avocado Roll", "Uramaki de salmon y aguacate"],
    type: "URAMAKI",
    shortDescription: "Uramaki de salmon y aguacate.",
    ingredients: ["salmon", "aguacate", "arroz de sushi", "nori"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Suave y cremosa",
    origin: "Combinacion habitual en Europa.",
    popularity: 88,
  },
  {
    name: "Tuna Avocado Uramaki",
    japaneseName: null,
    aliases: ["Tuna Avocado Roll", "Uramaki de atun y aguacate"],
    type: "URAMAKI",
    shortDescription: "Uramaki de atun y aguacate.",
    ingredients: ["atun", "aguacate", "arroz de sushi", "nori"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Firme y cremosa",
    origin: "Combinacion habitual en menus occidentales.",
    popularity: 80,
  },
  {
    name: "Ebi Tempura Uramaki",
    japaneseName: null,
    aliases: ["Shrimp Tempura Uramaki", "Uramaki de langostino tempura"],
    type: "URAMAKI",
    shortDescription: `Uramaki con langostino tempura. ${variationNote}`,
    ingredients: ["langostino tempura", "aguacate o pepino", "arroz de sushi", "nori"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "BOLD",
    texture: "Crujiente y cremosa",
    origin: "Muy comun en delivery europeo.",
    popularity: 91,
  },
  {
    name: "Philadelphia Uramaki",
    japaneseName: null,
    aliases: ["Philadelphia Roll", "Philly Roll", "Uramaki Philadelphia"],
    type: "URAMAKI",
    shortDescription: `Uramaki con queso crema, normalmente salmon. ${variationNote}`,
    ingredients: ["salmon", "queso crema", "pepino o aguacate", "arroz de sushi", "nori"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "BOLD",
    texture: "Muy cremosa",
    origin: "Roll occidental muy extendido.",
    popularity: 90,
  },
  {
    name: "Spicy Tuna Uramaki",
    japaneseName: null,
    aliases: ["Spicy Tuna Roll", "Uramaki picante de atun"],
    type: "URAMAKI",
    shortDescription: "Uramaki de atun con salsa picante.",
    ingredients: ["atun", "mayonesa picante", "arroz de sushi", "nori"],
    rawFish: true,
    spicyLevel: "MEDIUM",
    flavorIntensity: "BOLD",
    texture: "Cremosa y picante",
    origin: "Fusion occidental muy comun.",
    popularity: 87,
  },
  {
    name: "Spicy Salmon Uramaki",
    japaneseName: null,
    aliases: ["Spicy Salmon Roll", "Uramaki picante de salmon"],
    type: "URAMAKI",
    shortDescription: "Uramaki de salmon con salsa picante.",
    ingredients: ["salmon", "mayonesa picante", "arroz de sushi", "nori"],
    rawFish: true,
    spicyLevel: "MEDIUM",
    flavorIntensity: "BOLD",
    texture: "Cremosa y jugosa",
    origin: "Fusion occidental muy comun.",
    popularity: 84,
  },
  {
    name: "Unagi Avocado Uramaki",
    japaneseName: null,
    aliases: ["Eel Avocado Roll", "Uramaki de anguila y aguacate"],
    type: "URAMAKI",
    shortDescription: "Uramaki de anguila cocinada y aguacate.",
    ingredients: ["anguila cocinada", "aguacate", "arroz de sushi", "nori", "salsa unagi"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "BOLD",
    texture: "Melosa y cremosa",
    origin: "Combinacion frecuente en cartas occidentales.",
    popularity: 76,
  },
  {
    name: "Chicken Teriyaki Uramaki",
    japaneseName: null,
    aliases: ["Chicken Roll", "Uramaki de pollo teriyaki"],
    type: "URAMAKI",
    shortDescription: `Uramaki con pollo teriyaki. ${variationNote}`,
    ingredients: ["pollo teriyaki", "pepino o aguacate", "arroz de sushi", "nori"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "BOLD",
    texture: "Tierna y compacta",
    origin: "Fusion frecuente en restaurantes europeos.",
    popularity: 65,
  },
  {
    name: "Salmon Cheese Uramaki",
    japaneseName: null,
    aliases: ["Uramaki salmon queso", "Salmon Cream Cheese Roll"],
    type: "URAMAKI",
    shortDescription: "Uramaki de salmon con queso crema.",
    ingredients: ["salmon", "queso crema", "arroz de sushi", "nori"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Cremosa",
    origin: "Adaptacion occidental muy comun.",
    popularity: 77,
  },
  {
    name: "Tuna Mango Uramaki",
    japaneseName: null,
    aliases: ["Uramaki atun mango", "Tuna Mango Roll"],
    type: "URAMAKI",
    shortDescription: `Uramaki de atun con mango. ${variationNote}`,
    ingredients: ["atun", "mango", "arroz de sushi", "nori"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Firme y jugosa",
    origin: "Fusion moderna frecuente en Europa.",
    popularity: 58,
  },
  {
    name: "Salmon Mango Uramaki",
    japaneseName: null,
    aliases: ["Uramaki salmon mango", "Salmon Mango Roll"],
    type: "URAMAKI",
    shortDescription: `Uramaki de salmon con mango. ${variationNote}`,
    ingredients: ["salmon", "mango", "arroz de sushi", "nori"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Suave y jugosa",
    origin: "Fusion moderna frecuente en Europa.",
    popularity: 62,
  },
  {
    name: "Vegetable Uramaki",
    japaneseName: null,
    aliases: ["Veggie Uramaki", "Uramaki vegetal"],
    type: "URAMAKI",
    shortDescription: `Uramaki vegetal con rellenos frescos. ${variationNote}`,
    ingredients: ["aguacate", "pepino", "zanahoria", "arroz de sushi", "nori"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "DELICATE",
    texture: "Crujiente y fresca",
    origin: "Opcion vegetariana habitual.",
    popularity: 70,
  },
  {
    name: "Wakame Uramaki",
    japaneseName: null,
    aliases: ["Seaweed Uramaki", "Uramaki de wakame"],
    type: "URAMAKI",
    shortDescription: "Uramaki con ensalada de wakame.",
    ingredients: ["wakame", "aguacate opcional", "arroz de sushi", "nori"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Jugosa y fresca",
    origin: "Opcion vegetal en cartas europeas.",
    popularity: 52,
  },
  {
    name: "Surimi Uramaki",
    japaneseName: null,
    aliases: ["Crab Stick Uramaki", "Uramaki de surimi"],
    type: "URAMAKI",
    shortDescription: `Uramaki con surimi y verduras. ${variationNote}`,
    ingredients: ["surimi", "aguacate o pepino", "arroz de sushi", "nori"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Suave y fresca",
    origin: "Muy comun en bandejas de sushi occidental.",
    popularity: 72,
  },
  {
    name: "Prawn Avocado Uramaki",
    japaneseName: null,
    aliases: ["Ebi Avocado Roll", "Uramaki de gamba y aguacate"],
    type: "URAMAKI",
    shortDescription: "Uramaki de langostino cocido y aguacate.",
    ingredients: ["langostino cocido", "aguacate", "arroz de sushi", "nori"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Tierna y cremosa",
    origin: "Opcion sin pescado crudo muy habitual.",
    popularity: 74,
  },
  {
    name: "Pez Mantequilla Uramaki",
    japaneseName: null,
    aliases: ["Butterfish Uramaki", "Uramaki de pez mantequilla"],
    type: "URAMAKI",
    shortDescription: `Uramaki con pez mantequilla. ${variationNote}`,
    ingredients: ["pez mantequilla", "aguacate o pepino", "arroz de sushi", "nori"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Mantecosa",
    origin: "Muy comun en restaurantes espanoles de sushi.",
    popularity: 68,
  },
  {
    name: "Foie Uramaki",
    japaneseName: null,
    aliases: ["Uramaki de foie", "Foie Roll"],
    type: "URAMAKI",
    shortDescription: `Uramaki fusion con foie y salsa dulce. ${variationNote}`,
    ingredients: ["foie", "arroz de sushi", "nori", "salsa dulce"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "BOLD",
    texture: "Untuosa",
    origin: "Fusion frecuente en restaurantes espanoles.",
    popularity: 55,
  },
  {
    name: "Duck Uramaki",
    japaneseName: null,
    aliases: ["Pato Uramaki", "Duck Roll"],
    type: "URAMAKI",
    shortDescription: `Uramaki fusion con pato. ${variationNote}`,
    ingredients: ["pato", "pepino", "arroz de sushi", "nori", "salsa hoisin opcional"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "BOLD",
    texture: "Tierna y densa",
    origin: "Fusion asiatica presente en algunos menus europeos.",
    popularity: 49,
  },
  {
    name: "Tempura Vegetable Uramaki",
    japaneseName: null,
    aliases: ["Uramaki vegetal tempura", "Vegetable Tempura Roll"],
    type: "URAMAKI",
    shortDescription: `Uramaki con verduras en tempura. ${variationNote}`,
    ingredients: ["verduras tempura", "arroz de sushi", "nori", "salsa opcional"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Crujiente",
    origin: "Opcion vegetariana de estilo fusion.",
    popularity: 57,
  },

  {
    name: "Sake Temaki",
    japaneseName: "sake temaki",
    aliases: ["Salmon Temaki", "Temaki de salmon"],
    type: "TEMAKI",
    shortDescription: "Cono de nori con salmon y arroz.",
    ingredients: ["salmon", "arroz de sushi", "nori", "aguacate opcional"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Crujiente por fuera y suave por dentro",
    origin: "Temaki clasico frecuente.",
    popularity: 82,
  },
  {
    name: "Maguro Temaki",
    japaneseName: "maguro temaki",
    aliases: ["Tuna Temaki", "Temaki de atun"],
    type: "TEMAKI",
    shortDescription: "Cono de nori con atun.",
    ingredients: ["atun", "arroz de sushi", "nori", "pepino opcional"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Firme y crujiente",
    origin: "Temaki clasico japones.",
    popularity: 72,
  },
  {
    name: "Spicy Tuna Temaki",
    japaneseName: null,
    aliases: ["Temaki picante de atun", "Tuna Spicy Temaki"],
    type: "TEMAKI",
    shortDescription: "Temaki de atun con salsa picante.",
    ingredients: ["atun", "salsa picante", "arroz de sushi", "nori"],
    rawFish: true,
    spicyLevel: "MEDIUM",
    flavorIntensity: "BOLD",
    texture: "Cremosa y crujiente",
    origin: "Fusion muy comun en menus occidentales.",
    popularity: 78,
  },
  {
    name: "California Temaki",
    japaneseName: null,
    aliases: ["Temaki California", "California Hand Roll"],
    type: "TEMAKI",
    shortDescription: `Temaki con relleno tipo California. ${variationNote}`,
    ingredients: ["surimi o cangrejo", "aguacate", "pepino", "arroz de sushi", "nori"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Cremosa y fresca",
    origin: "Adaptacion occidental muy comun.",
    popularity: 76,
  },
  {
    name: "Ebi Tempura Temaki",
    japaneseName: null,
    aliases: ["Tempura Prawn Temaki", "Temaki de gamba tempura"],
    type: "TEMAKI",
    shortDescription: "Temaki con langostino tempura.",
    ingredients: ["langostino tempura", "arroz de sushi", "nori", "salsa opcional"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "BOLD",
    texture: "Crujiente y jugosa",
    origin: "Opcion cocinada habitual en delivery.",
    popularity: 75,
  },
  {
    name: "Unagi Temaki",
    japaneseName: "unagi temaki",
    aliases: ["Eel Temaki", "Temaki de anguila"],
    type: "TEMAKI",
    shortDescription: "Temaki con anguila cocinada.",
    ingredients: ["anguila cocinada", "pepino", "arroz de sushi", "nori", "salsa unagi"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "BOLD",
    texture: "Melosa y crujiente",
    origin: "Temaki basado en ingredientes clasicos japoneses.",
    popularity: 64,
  },
  {
    name: "Ikura Temaki",
    japaneseName: "ikura temaki",
    aliases: ["Salmon Roe Temaki", "Temaki de huevas de salmon"],
    type: "TEMAKI",
    shortDescription: "Temaki con huevas de salmon.",
    ingredients: ["ikura", "arroz de sushi", "nori", "pepino opcional"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "BOLD",
    texture: "Jugosa y crujiente",
    origin: "Temaki clasico en cartas amplias.",
    popularity: 58,
  },
  {
    name: "Negitoro Temaki",
    japaneseName: "negitoro temaki",
    aliases: ["Temaki de toro picado", "Chopped Tuna Temaki"],
    type: "TEMAKI",
    shortDescription: "Temaki de atun graso picado y cebolleta.",
    ingredients: ["atun graso picado", "cebolleta", "arroz de sushi", "nori"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "BOLD",
    texture: "Untuosa y crujiente",
    origin: "Clasico japones presente en sushi bars.",
    popularity: 61,
  },
  {
    name: "Vegetable Temaki",
    japaneseName: null,
    aliases: ["Veggie Temaki", "Temaki vegetal"],
    type: "TEMAKI",
    shortDescription: `Temaki vegetal con rellenos frescos. ${variationNote}`,
    ingredients: ["aguacate", "pepino", "zanahoria", "arroz de sushi", "nori"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "DELICATE",
    texture: "Crujiente y fresca",
    origin: "Opcion vegetariana habitual.",
    popularity: 63,
  },
  {
    name: "Wakame Temaki",
    japaneseName: null,
    aliases: ["Seaweed Temaki", "Temaki de wakame"],
    type: "TEMAKI",
    shortDescription: "Temaki con ensalada de wakame.",
    ingredients: ["wakame", "arroz de sushi", "nori", "sesamo opcional"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Jugosa y crujiente",
    origin: "Opcion vegetal en menus europeos.",
    popularity: 50,
  },
  {
    name: "Salmon Avocado Temaki",
    japaneseName: null,
    aliases: ["Temaki salmon aguacate", "Salmon Avocado Hand Roll"],
    type: "TEMAKI",
    shortDescription: "Temaki de salmon y aguacate.",
    ingredients: ["salmon", "aguacate", "arroz de sushi", "nori"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Suave y crujiente",
    origin: "Combinacion occidental frecuente.",
    popularity: 73,
  },
  {
    name: "Tuna Avocado Temaki",
    japaneseName: null,
    aliases: ["Temaki atun aguacate", "Tuna Avocado Hand Roll"],
    type: "TEMAKI",
    shortDescription: "Temaki de atun y aguacate.",
    ingredients: ["atun", "aguacate", "arroz de sushi", "nori"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Firme y crujiente",
    origin: "Combinacion occidental frecuente.",
    popularity: 66,
  },
  {
    name: "Chicken Temaki",
    japaneseName: null,
    aliases: ["Temaki de pollo", "Chicken Hand Roll"],
    type: "TEMAKI",
    shortDescription: `Temaki fusion con pollo cocinado. ${variationNote}`,
    ingredients: ["pollo cocinado", "arroz de sushi", "nori", "verduras"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Tierna y crujiente",
    origin: "Fusion frecuente en restaurantes de delivery.",
    popularity: 54,
  },
  {
    name: "Prawn Avocado Temaki",
    japaneseName: null,
    aliases: ["Temaki de gamba y aguacate", "Ebi Avocado Temaki"],
    type: "TEMAKI",
    shortDescription: "Temaki de langostino cocido y aguacate.",
    ingredients: ["langostino cocido", "aguacate", "arroz de sushi", "nori"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Tierna y crujiente",
    origin: "Opcion sin pescado crudo habitual.",
    popularity: 60,
  },

  {
    name: "Ikura Gunkan",
    japaneseName: "ikura gunkan",
    aliases: ["Salmon Roe Gunkan", "Gunkan de huevas de salmon"],
    type: "GUNKAN",
    shortDescription: "Gunkan con huevas de salmon.",
    ingredients: ["ikura", "arroz de sushi", "nori"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "BOLD",
    texture: "Jugosa y perlada",
    origin: "Gunkan clasico japones.",
    popularity: 78,
  },
  {
    name: "Tobiko Gunkan",
    japaneseName: "tobiko gunkan",
    aliases: ["Flying Fish Roe Gunkan", "Gunkan de tobiko"],
    type: "GUNKAN",
    shortDescription: "Gunkan con huevas de pez volador.",
    ingredients: ["tobiko", "arroz de sushi", "nori"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Crujiente y pequena",
    origin: "Comun en cartas de sushi variadas.",
    popularity: 74,
  },
  {
    name: "Masago Gunkan",
    japaneseName: "masago gunkan",
    aliases: ["Capelin Roe Gunkan", "Gunkan de masago"],
    type: "GUNKAN",
    shortDescription: "Gunkan con huevas de capelan.",
    ingredients: ["masago", "arroz de sushi", "nori"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Pequena y granulada",
    origin: "Alternativa comun a tobiko.",
    popularity: 55,
  },
  {
    name: "Spicy Tuna Gunkan",
    japaneseName: null,
    aliases: ["Gunkan picante de atun", "Tuna Gunkan"],
    type: "GUNKAN",
    shortDescription: "Gunkan de atun picado con salsa picante.",
    ingredients: ["atun picado", "salsa picante", "arroz de sushi", "nori"],
    rawFish: true,
    spicyLevel: "MEDIUM",
    flavorIntensity: "BOLD",
    texture: "Cremosa",
    origin: "Fusion frecuente en restaurantes occidentales.",
    popularity: 72,
  },
  {
    name: "Spicy Salmon Gunkan",
    japaneseName: null,
    aliases: ["Gunkan picante de salmon"],
    type: "GUNKAN",
    shortDescription: "Gunkan de salmon picado con salsa picante.",
    ingredients: ["salmon picado", "salsa picante", "arroz de sushi", "nori"],
    rawFish: true,
    spicyLevel: "MEDIUM",
    flavorIntensity: "BOLD",
    texture: "Cremosa y jugosa",
    origin: "Fusion frecuente en restaurantes occidentales.",
    popularity: 70,
  },
  {
    name: "Wakame Gunkan",
    japaneseName: null,
    aliases: ["Seaweed Gunkan", "Gunkan de wakame"],
    type: "GUNKAN",
    shortDescription: "Gunkan con ensalada de wakame.",
    ingredients: ["wakame", "arroz de sushi", "nori", "sesamo opcional"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Jugosa y crujiente",
    origin: "Opcion sin pescado muy vista en menus europeos.",
    popularity: 66,
  },
  {
    name: "Kani Salad Gunkan",
    japaneseName: null,
    aliases: ["Crab Salad Gunkan", "Gunkan de ensalada de cangrejo"],
    type: "GUNKAN",
    shortDescription: `Gunkan con ensalada de cangrejo o surimi. ${variationNote}`,
    ingredients: ["surimi o cangrejo", "mayonesa", "arroz de sushi", "nori"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Cremosa",
    origin: "Fusion muy comun en cartas occidentales.",
    popularity: 64,
  },
  {
    name: "Corn Gunkan",
    japaneseName: null,
    aliases: ["Corn Mayo Gunkan", "Gunkan de maiz"],
    type: "GUNKAN",
    shortDescription: "Gunkan con maiz y mayonesa.",
    ingredients: ["maiz", "mayonesa", "arroz de sushi", "nori"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "DELICATE",
    texture: "Cremosa y granulada",
    origin: "Opcion comun en kaiten sushi y menus casuales.",
    popularity: 40,
  },
  {
    name: "Tuna Mayo Gunkan",
    japaneseName: null,
    aliases: ["Gunkan de atun cocido", "Tuna Salad Gunkan"],
    type: "GUNKAN",
    shortDescription: "Gunkan con atun cocido y mayonesa.",
    ingredients: ["atun cocido", "mayonesa", "arroz de sushi", "nori"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Cremosa",
    origin: "Opcion casual frecuente.",
    popularity: 48,
  },
  {
    name: "Negitoro Gunkan",
    japaneseName: "negitoro gunkan",
    aliases: ["Chopped Tuna Gunkan", "Gunkan de toro picado"],
    type: "GUNKAN",
    shortDescription: "Gunkan con atun graso picado y cebolleta.",
    ingredients: ["atun graso picado", "cebolleta", "arroz de sushi", "nori"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "BOLD",
    texture: "Untuosa",
    origin: "Clasico japones en sushi bars.",
    popularity: 58,
  },
  {
    name: "Scallop Gunkan",
    japaneseName: "hotate gunkan",
    aliases: ["Hotate Gunkan", "Gunkan de vieira"],
    type: "GUNKAN",
    shortDescription: `Gunkan con vieira picada o alinada. ${variationNote}`,
    ingredients: ["vieira", "arroz de sushi", "nori", "salsa opcional"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "DELICATE",
    texture: "Cremosa y suave",
    origin: "Pieza de carta amplia o premium.",
    popularity: 50,
  },
  {
    name: "Salmon Tartar Gunkan",
    japaneseName: null,
    aliases: ["Gunkan tartar de salmon", "Salmon Tartare Gunkan"],
    type: "GUNKAN",
    shortDescription: `Gunkan con tartar de salmon. ${variationNote}`,
    ingredients: ["salmon picado", "salsa", "arroz de sushi", "nori"],
    rawFish: true,
    spicyLevel: "MILD",
    flavorIntensity: "BALANCED",
    texture: "Cremosa y jugosa",
    origin: "Fusion frecuente en Europa.",
    popularity: 68,
  },
  {
    name: "Tuna Tartar Gunkan",
    japaneseName: null,
    aliases: ["Gunkan tartar de atun", "Tuna Tartare Gunkan"],
    type: "GUNKAN",
    shortDescription: `Gunkan con tartar de atun. ${variationNote}`,
    ingredients: ["atun picado", "salsa", "arroz de sushi", "nori"],
    rawFish: true,
    spicyLevel: "MILD",
    flavorIntensity: "BOLD",
    texture: "Cremosa y firme",
    origin: "Fusion frecuente en Europa.",
    popularity: 66,
  },
  {
    name: "Avocado Gunkan",
    japaneseName: null,
    aliases: ["Gunkan de aguacate"],
    type: "GUNKAN",
    shortDescription: `Gunkan vegetal con aguacate. ${variationNote}`,
    ingredients: ["aguacate", "arroz de sushi", "nori", "salsa opcional"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "DELICATE",
    texture: "Cremosa",
    origin: "Adaptacion vegetal en cartas occidentales.",
    popularity: 44,
  },

  {
    name: "Sake Sashimi",
    japaneseName: "sake sashimi",
    aliases: ["Salmon Sashimi", "Sashimi de salmon"],
    type: "SASHIMI",
    shortDescription: "Cortes de salmon sin arroz.",
    ingredients: ["salmon"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Suave y melosa",
    origin: "Uno de los sashimi mas pedidos en Europa.",
    popularity: 95,
  },
  {
    name: "Maguro Sashimi",
    japaneseName: "maguro sashimi",
    aliases: ["Tuna Sashimi", "Sashimi de atun"],
    type: "SASHIMI",
    shortDescription: "Cortes de atun sin arroz.",
    ingredients: ["atun"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Firme y sedosa",
    origin: "Clasico japones muy comun.",
    popularity: 92,
  },
  {
    name: "Toro Sashimi",
    japaneseName: "toro sashimi",
    aliases: ["Fatty Tuna Sashimi", "Sashimi de ventresca de atun"],
    type: "SASHIMI",
    shortDescription: "Cortes de ventresca de atun.",
    ingredients: ["ventresca de atun"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "BOLD",
    texture: "Muy melosa",
    origin: "Producto premium en sushi bars.",
    popularity: 70,
  },
  {
    name: "Hamachi Sashimi",
    japaneseName: "hamachi sashimi",
    aliases: ["Yellowtail Sashimi", "Sashimi de hamachi"],
    type: "SASHIMI",
    shortDescription: "Cortes de hamachi sin arroz.",
    ingredients: ["hamachi"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "DELICATE",
    texture: "Mantecosa",
    origin: "Habitual en cartas amplias.",
    popularity: 76,
  },
  {
    name: "Suzuki Sashimi",
    japaneseName: "suzuki sashimi",
    aliases: ["Sea Bass Sashimi", "Sashimi de lubina"],
    type: "SASHIMI",
    shortDescription: "Cortes de lubina sin arroz.",
    ingredients: ["lubina"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "DELICATE",
    texture: "Firme y ligera",
    origin: "Pescado blanco frecuente en Europa.",
    popularity: 62,
  },
  {
    name: "Tai Sashimi",
    japaneseName: "tai sashimi",
    aliases: ["Sea Bream Sashimi", "Sashimi de dorada"],
    type: "SASHIMI",
    shortDescription: "Cortes de dorada sin arroz.",
    ingredients: ["dorada"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "DELICATE",
    texture: "Firme y limpia",
    origin: "Pescado blanco clasico en Japon.",
    popularity: 56,
  },
  {
    name: "Saba Sashimi",
    japaneseName: "saba sashimi",
    aliases: ["Mackerel Sashimi", "Sashimi de caballa"],
    type: "SASHIMI",
    shortDescription: "Cortes de caballa, a menudo curada.",
    ingredients: ["caballa"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "BOLD",
    texture: "Firme y grasa",
    origin: "Clasico japones de sabor intenso.",
    popularity: 50,
  },
  {
    name: "Ika Sashimi",
    japaneseName: "ika sashimi",
    aliases: ["Squid Sashimi", "Sashimi de calamar"],
    type: "SASHIMI",
    shortDescription: "Cortes de calamar sin arroz.",
    ingredients: ["calamar"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "DELICATE",
    texture: "Suave y elastica",
    origin: "Clasico japones en cartas especializadas.",
    popularity: 49,
  },
  {
    name: "Tako Sashimi",
    japaneseName: "tako sashimi",
    aliases: ["Octopus Sashimi", "Sashimi de pulpo"],
    type: "SASHIMI",
    shortDescription: "Cortes de pulpo cocido sin arroz.",
    ingredients: ["pulpo cocido"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Firme y elastica",
    origin: "Comun en menus japoneses y mixtos.",
    popularity: 58,
  },
  {
    name: "Hotate Sashimi",
    japaneseName: "hotate sashimi",
    aliases: ["Scallop Sashimi", "Sashimi de vieira"],
    type: "SASHIMI",
    shortDescription: "Cortes de vieira sin arroz.",
    ingredients: ["vieira"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "DELICATE",
    texture: "Sedosa y dulce",
    origin: "Producto frecuente en cartas premium.",
    popularity: 60,
  },
  {
    name: "Amaebi Sashimi",
    japaneseName: "amaebi sashimi",
    aliases: ["Sweet Shrimp Sashimi", "Sashimi de gamba dulce"],
    type: "SASHIMI",
    shortDescription: "Gamba dulce servida sin arroz.",
    ingredients: ["gamba dulce"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "DELICATE",
    texture: "Suave y dulce",
    origin: "Comun en sushi bars con producto variado.",
    popularity: 52,
  },
  {
    name: "Unagi Sashimi",
    japaneseName: "unagi sashimi",
    aliases: ["Eel Sashimi", "Anguila sin arroz"],
    type: "SASHIMI",
    shortDescription: "Anguila cocinada servida sin arroz.",
    ingredients: ["anguila cocinada", "salsa unagi opcional"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "BOLD",
    texture: "Melosa",
    origin: "Menos frecuente que el nigiri de unagi.",
    popularity: 45,
  },
  {
    name: "Pez Mantequilla Sashimi",
    japaneseName: null,
    aliases: ["Butterfish Sashimi", "Escolar Sashimi"],
    type: "SASHIMI",
    shortDescription: "Cortes de pez mantequilla sin arroz.",
    ingredients: ["pez mantequilla"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Mantecosa",
    origin: "Muy comun en cartas espanolas.",
    popularity: 72,
  },
  {
    name: "Tataki de Atun",
    japaneseName: "maguro tataki",
    aliases: ["Tuna Tataki", "Atun tataki"],
    type: "SASHIMI",
    shortDescription: "Atun sellado por fuera y crudo en el centro.",
    ingredients: ["atun sellado", "sesamo opcional", "salsa ponzu opcional"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "BOLD",
    texture: "Firme y jugosa",
    origin: "Preparacion japonesa frecuente en restaurantes europeos.",
    popularity: 78,
  },
  {
    name: "Tataki de Salmon",
    japaneseName: "sake tataki",
    aliases: ["Salmon Tataki", "Salmon tataki"],
    type: "SASHIMI",
    shortDescription: "Salmon sellado por fuera y crudo en el centro.",
    ingredients: ["salmon sellado", "sesamo opcional", "salsa ponzu opcional"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Jugosa y suave",
    origin: "Preparacion muy comun en cartas europeas.",
    popularity: 80,
  },
  {
    name: "Sashimi Mixto",
    japaneseName: "sashimi moriawase",
    aliases: ["Mixed Sashimi", "Surtido de sashimi"],
    type: "SASHIMI",
    shortDescription: `Surtido de cortes de pescado y marisco. ${variationNote}`,
    ingredients: ["pescados variados", "mariscos variados"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Variada",
    origin: "Formato habitual para compartir.",
    popularity: 90,
  },
  {
    name: "Sashimi de Vieira Flambeada",
    japaneseName: null,
    aliases: ["Aburi Scallop Sashimi", "Vieira aburi"],
    type: "SASHIMI",
    shortDescription: "Vieira ligeramente flameada, servida sin arroz.",
    ingredients: ["vieira flameada", "salsa opcional"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Suave y cremosa",
    origin: "Estilo aburi moderno.",
    popularity: 46,
  },
  {
    name: "Sashimi de Lubina con Ponzu",
    japaneseName: null,
    aliases: ["Sea Bass Ponzu Sashimi", "Lubina ponzu"],
    type: "SASHIMI",
    shortDescription: `Lubina cortada fina con salsa ponzu. ${variationNote}`,
    ingredients: ["lubina", "salsa ponzu", "cebolleta opcional"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Ligera y fresca",
    origin: "Preparacion comun en restaurantes modernos.",
    popularity: 48,
  },
  {
    name: "Sashimi de Salmon Picante",
    japaneseName: null,
    aliases: ["Spicy Salmon Sashimi", "Salmon sashimi spicy"],
    type: "SASHIMI",
    shortDescription: `Cortes de salmon con salsa picante. ${variationNote}`,
    ingredients: ["salmon", "salsa picante", "sesamo opcional"],
    rawFish: true,
    spicyLevel: "MEDIUM",
    flavorIntensity: "BOLD",
    texture: "Suave y picante",
    origin: "Fusion occidental.",
    popularity: 63,
  },
  {
    name: "Sashimi de Atun Picante",
    japaneseName: null,
    aliases: ["Spicy Tuna Sashimi", "Atun sashimi spicy"],
    type: "SASHIMI",
    shortDescription: `Cortes de atun con salsa picante. ${variationNote}`,
    ingredients: ["atun", "salsa picante", "sesamo opcional"],
    rawFish: true,
    spicyLevel: "MEDIUM",
    flavorIntensity: "BOLD",
    texture: "Firme y picante",
    origin: "Fusion occidental.",
    popularity: 61,
  },

  {
    name: "Inari Sushi",
    japaneseName: "inarizushi",
    aliases: ["Inari", "Tofu Pouch Sushi"],
    type: "INARI",
    shortDescription: "Bolsa de tofu frito dulce rellena de arroz.",
    ingredients: ["tofu frito sazonado", "arroz de sushi"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Suave y jugosa",
    origin: "Clasico japones y opcion vegetariana frecuente.",
    popularity: 72,
  },
  {
    name: "Inari Wakame",
    japaneseName: null,
    aliases: ["Seaweed Inari", "Inari de wakame"],
    type: "INARI",
    shortDescription: "Inari relleno o coronado con wakame.",
    ingredients: ["tofu frito sazonado", "arroz de sushi", "wakame"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Jugosa",
    origin: "Adaptacion vegetal comun.",
    popularity: 50,
  },
  {
    name: "Inari Salmon",
    japaneseName: null,
    aliases: ["Salmon Inari", "Inari de salmon"],
    type: "INARI",
    shortDescription: `Inari con salmon como topping o relleno. ${variationNote}`,
    ingredients: ["tofu frito sazonado", "arroz de sushi", "salmon"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Jugosa y suave",
    origin: "Fusion moderna en cartas europeas.",
    popularity: 55,
  },
  {
    name: "Inari Tuna Mayo",
    japaneseName: null,
    aliases: ["Tuna Mayo Inari", "Inari de atun con mayonesa"],
    type: "INARI",
    shortDescription: "Inari con atun cocido y mayonesa.",
    ingredients: ["tofu frito sazonado", "arroz de sushi", "atun cocido", "mayonesa"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Cremosa y jugosa",
    origin: "Opcion casual inspirada en kaiten sushi.",
    popularity: 46,
  },
  {
    name: "Inari Kani",
    japaneseName: null,
    aliases: ["Crab Inari", "Inari de cangrejo"],
    type: "INARI",
    shortDescription: `Inari con cangrejo o surimi. ${variationNote}`,
    ingredients: ["tofu frito sazonado", "arroz de sushi", "cangrejo o surimi"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Suave y jugosa",
    origin: "Adaptacion occidental frecuente.",
    popularity: 48,
  },
  {
    name: "Inari Avocado",
    japaneseName: null,
    aliases: ["Avocado Inari", "Inari de aguacate"],
    type: "INARI",
    shortDescription: "Inari vegetal con aguacate.",
    ingredients: ["tofu frito sazonado", "arroz de sushi", "aguacate"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "DELICATE",
    texture: "Cremosa y jugosa",
    origin: "Adaptacion vegetal moderna.",
    popularity: 45,
  },
  {
    name: "Inari Tamago",
    japaneseName: null,
    aliases: ["Tamago Inari", "Inari de tortilla japonesa"],
    type: "INARI",
    shortDescription: "Inari con tortilla japonesa.",
    ingredients: ["tofu frito sazonado", "arroz de sushi", "tamago"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "DELICATE",
    texture: "Suave y esponjosa",
    origin: "Opcion sin pescado de inspiracion japonesa.",
    popularity: 43,
  },

  {
    name: "Chirashi Bowl",
    japaneseName: "chirashizushi",
    aliases: ["Chirashi", "Sushi Bowl"],
    type: "CHIRASHI",
    shortDescription: `Bol de arroz con pescado y toppings variados. ${variationNote}`,
    ingredients: ["arroz de sushi", "pescados variados", "verduras", "toppings variables"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Variada y abundante",
    origin: "Plato japones adaptado al formato bowl.",
    popularity: 84,
  },
  {
    name: "Salmon Chirashi",
    japaneseName: "sake chirashi",
    aliases: ["Chirashi de salmon", "Salmon Sushi Bowl"],
    type: "CHIRASHI",
    shortDescription: "Bol de arroz de sushi con salmon.",
    ingredients: ["salmon", "arroz de sushi", "aguacate opcional", "toppings opcionales"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Suave y abundante",
    origin: "Muy comun en cartas con sushi bowls.",
    popularity: 80,
  },
  {
    name: "Tuna Chirashi",
    japaneseName: "maguro chirashi",
    aliases: ["Chirashi de atun", "Tuna Sushi Bowl"],
    type: "CHIRASHI",
    shortDescription: "Bol de arroz de sushi con atun.",
    ingredients: ["atun", "arroz de sushi", "aguacate opcional", "toppings opcionales"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Firme y abundante",
    origin: "Frecuente en cartas amplias.",
    popularity: 76,
  },
  {
    name: "Mixed Chirashi",
    japaneseName: "chirashi moriawase",
    aliases: ["Chirashi mixto", "Mixed Sushi Bowl"],
    type: "CHIRASHI",
    shortDescription: `Bol con varios pescados y mariscos. ${variationNote}`,
    ingredients: ["arroz de sushi", "pescados variados", "mariscos variados", "toppings variables"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Variada",
    origin: "Formato comun para probar varios cortes.",
    popularity: 79,
  },
  {
    name: "Vegetable Chirashi",
    japaneseName: null,
    aliases: ["Chirashi vegetal", "Veggie Sushi Bowl"],
    type: "CHIRASHI",
    shortDescription: `Bol de arroz de sushi con toppings vegetales. ${variationNote}`,
    ingredients: ["arroz de sushi", "aguacate", "pepino", "wakame", "verduras"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "DELICATE",
    texture: "Fresca y variada",
    origin: "Adaptacion vegetal moderna.",
    popularity: 58,
  },
  {
    name: "Poke Style Chirashi",
    japaneseName: null,
    aliases: ["Poke Chirashi", "Chirashi estilo poke"],
    type: "CHIRASHI",
    shortDescription: `Bol fusion entre chirashi y poke. ${variationNote}`,
    ingredients: ["arroz", "pescado o tofu", "aguacate", "edamame", "salsas"],
    rawFish: true,
    spicyLevel: "MILD",
    flavorIntensity: "BOLD",
    texture: "Variada y jugosa",
    origin: "Fusion moderna frecuente en Europa.",
    popularity: 63,
  },
  {
    name: "Unagi Chirashi",
    japaneseName: null,
    aliases: ["Eel Chirashi", "Chirashi de anguila"],
    type: "CHIRASHI",
    shortDescription: "Bol de arroz con anguila cocinada.",
    ingredients: ["anguila cocinada", "arroz de sushi", "salsa unagi", "toppings opcionales"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "BOLD",
    texture: "Melosa y abundante",
    origin: "Inspirado en platos japoneses de anguila sobre arroz.",
    popularity: 57,
  },

  {
    name: "Dragon Roll",
    japaneseName: null,
    aliases: ["Dragon Maki", "Dragon Uramaki"],
    type: "WESTERN_ROLLS",
    shortDescription: `Roll occidental vistoso con cobertura de aguacate o anguila. ${variationNote}`,
    ingredients: ["aguacate o anguila", "langostino tempura frecuente", "arroz de sushi", "nori", "salsa unagi"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "BOLD",
    texture: "Cremosa y jugosa",
    origin: "Roll fusion occidental frecuente en delivery.",
    popularity: 95,
  },
  {
    name: "Rainbow Roll",
    japaneseName: null,
    aliases: ["Rainbow Maki", "Rainbow Uramaki"],
    type: "WESTERN_ROLLS",
    shortDescription: `Roll cubierto con varios pescados y aguacate. ${variationNote}`,
    ingredients: ["pescados variados", "aguacate", "surimi o cangrejo frecuente", "arroz de sushi", "nori"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Suave y variada",
    origin: "Roll occidental muy popular.",
    popularity: 92,
  },
  {
    name: "Alaska Roll",
    japaneseName: null,
    aliases: ["Alaska Maki", "Alaska Uramaki"],
    type: "WESTERN_ROLLS",
    shortDescription: `Roll occidental con salmon como ingrediente habitual. ${variationNote}`,
    ingredients: ["salmon", "aguacate", "pepino opcional", "arroz de sushi", "nori"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Cremosa y fresca",
    origin: "Roll de estilo americano frecuente en Europa.",
    popularity: 82,
  },
  {
    name: "Boston Roll",
    japaneseName: null,
    aliases: ["Boston Maki", "Boston Uramaki"],
    type: "WESTERN_ROLLS",
    shortDescription: `Roll occidental con langostino cocido como base habitual. ${variationNote}`,
    ingredients: ["langostino cocido", "aguacate", "pepino", "arroz de sushi", "nori"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Fresca y suave",
    origin: "Roll americano presente en muchas cartas.",
    popularity: 76,
  },
  {
    name: "Crunchy Roll",
    japaneseName: null,
    aliases: ["Crunch Roll", "Roll crujiente"],
    type: "WESTERN_ROLLS",
    shortDescription: `Roll con topping o relleno crujiente. ${variationNote}`,
    ingredients: ["topping crujiente", "relleno variable", "arroz de sushi", "nori"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "BOLD",
    texture: "Crujiente",
    origin: "Nombre comercial muy comun en delivery.",
    popularity: 88,
  },
  {
    name: "Spider Roll",
    japaneseName: null,
    aliases: ["Soft Shell Crab Roll", "Spider Maki"],
    type: "WESTERN_ROLLS",
    shortDescription: `Roll con cangrejo de concha blanda frito. ${variationNote}`,
    ingredients: ["soft shell crab", "pepino o lechuga", "arroz de sushi", "nori"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "BOLD",
    texture: "Crujiente y jugosa",
    origin: "Roll japones-americano frecuente en cartas amplias.",
    popularity: 75,
  },
  {
    name: "Volcano Roll",
    japaneseName: null,
    aliases: ["Volcano Maki", "Roll volcan"],
    type: "WESTERN_ROLLS",
    shortDescription: `Roll con topping cremoso, caliente o picante. ${variationNote}`,
    ingredients: ["relleno variable", "topping cremoso", "salsa picante opcional", "arroz de sushi", "nori"],
    rawFish: false,
    spicyLevel: "MEDIUM",
    flavorIntensity: "BOLD",
    texture: "Cremosa y densa",
    origin: "Fusion occidental muy comun en menus modernos.",
    popularity: 79,
  },
  {
    name: "Dynamite Roll",
    japaneseName: null,
    aliases: ["Dynamite Maki", "Roll dinamita"],
    type: "WESTERN_ROLLS",
    shortDescription: `Roll occidental con salsa picante o topping caliente. ${variationNote}`,
    ingredients: ["langostino o marisco frecuente", "salsa picante", "arroz de sushi", "nori"],
    rawFish: false,
    spicyLevel: "MEDIUM",
    flavorIntensity: "BOLD",
    texture: "Jugosa y cremosa",
    origin: "Roll de estilo americano frecuente.",
    popularity: 78,
  },
  {
    name: "Tiger Roll",
    japaneseName: null,
    aliases: ["Tiger Maki", "Tiger Uramaki"],
    type: "WESTERN_ROLLS",
    shortDescription: `Roll con langostino y cobertura vistosa. ${variationNote}`,
    ingredients: ["langostino frecuente", "aguacate", "arroz de sushi", "nori", "salsa opcional"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Cremosa y compacta",
    origin: "Nombre comercial frecuente en restaurantes fusion.",
    popularity: 74,
  },
  {
    name: "Caterpillar Roll",
    japaneseName: null,
    aliases: ["Caterpillar Maki", "Roll caterpillar"],
    type: "WESTERN_ROLLS",
    shortDescription: `Roll cubierto normalmente con aguacate. ${variationNote}`,
    ingredients: ["aguacate", "anguila o relleno variable", "arroz de sushi", "nori", "salsa unagi opcional"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "BOLD",
    texture: "Cremosa",
    origin: "Roll occidental de presentacion vistosa.",
    popularity: 66,
  },
  {
    name: "Hot Philadelphia Roll",
    japaneseName: null,
    aliases: ["Philadelphia Tempura Roll", "Roll Philadelphia caliente"],
    type: "WESTERN_ROLLS",
    shortDescription: `Version caliente o rebozada del Philadelphia Roll. ${variationNote}`,
    ingredients: ["salmon", "queso crema", "tempura o rebozado", "arroz de sushi", "nori"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "BOLD",
    texture: "Crujiente y cremosa",
    origin: "Fusion de delivery muy frecuente en Europa.",
    popularity: 73,
  },
  {
    name: "Las Vegas Roll",
    japaneseName: null,
    aliases: ["Vegas Roll", "Las Vegas Maki"],
    type: "WESTERN_ROLLS",
    shortDescription: `Roll occidental habitualmente frito o con queso crema. ${variationNote}`,
    ingredients: ["salmon o pescado variable", "queso crema frecuente", "tempura opcional", "arroz de sushi", "nori"],
    rawFish: false,
    spicyLevel: "NONE",
    flavorIntensity: "BOLD",
    texture: "Crujiente y densa",
    origin: "Roll comercial de estilo americano.",
    popularity: 60,
  },
  {
    name: "Sakura Roll",
    japaneseName: null,
    aliases: ["Sakura Maki", "Roll Sakura"],
    type: "WESTERN_ROLLS",
    shortDescription: `Nombre comercial usado para rolls con salmon, atun o toppings vistosos. ${variationNote}`,
    ingredients: ["relleno variable", "salmon frecuente", "arroz de sushi", "nori", "salsa opcional"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "BALANCED",
    texture: "Suave y variable",
    origin: "Nombre de carta frecuente, no receta tradicional unica.",
    popularity: 58,
  },
  {
    name: "Crazy Salmon Roll",
    japaneseName: null,
    aliases: ["Crazy Sake Roll", "Roll salmon crazy"],
    type: "WESTERN_ROLLS",
    shortDescription: `Roll occidental centrado en salmon con salsas o toppings. ${variationNote}`,
    ingredients: ["salmon", "aguacate o queso crema", "salsa variable", "arroz de sushi", "nori"],
    rawFish: true,
    spicyLevel: "MILD",
    flavorIntensity: "BOLD",
    texture: "Cremosa y jugosa",
    origin: "Nombre comercial frecuente en restaurantes fusion.",
    popularity: 69,
  },
  {
    name: "Rock and Roll",
    japaneseName: null,
    aliases: ["Rock Roll", "Rock & Roll Sushi"],
    type: "WESTERN_ROLLS",
    shortDescription: `Roll comercial con anguila, salmon o relleno variable segun carta. ${variationNote}`,
    ingredients: ["relleno variable", "anguila o salmon frecuente", "arroz de sushi", "nori", "salsa opcional"],
    rawFish: true,
    spicyLevel: "NONE",
    flavorIntensity: "BOLD",
    texture: "Variable",
    origin: "Nombre occidental sin receta universal.",
    popularity: 52,
  },
];

export const sushiSeedCatalog = rawCatalog.map(entry);

const duplicateSlugs = sushiSeedCatalog
  .map((item) => item.slug)
  .filter((slug, index, slugs) => slugs.indexOf(slug) !== index);

if (duplicateSlugs.length > 0) {
  throw new Error(`Duplicate sushi slugs found: ${duplicateSlugs.join(", ")}`);
}

if (sushiSeedCatalog.length !== 150) {
  throw new Error(`Expected 150 sushi seed records, received ${sushiSeedCatalog.length}.`);
}

export const sushiSeedStats = {
  total: sushiSeedCatalog.length,
  rawFishCount: sushiSeedCatalog.filter((sushi) => sushi.rawFish).length,
};

export type SushiSeedRecord = (typeof sushiSeedCatalog)[number];
